using System.Text;
using System.Text.RegularExpressions;

namespace Xur.Control;

internal sealed record ConsoleKeyboardOverlayView(ConsoleKeyboardPreview Preview,char? Feedback);

// Deadlines are observed when a display pulls its frame; no animation task,
// input activity or diagnostic revision is generated by transient feedback.
internal sealed class ConsoleKeyboardOverlay(TimeProvider? clock=null)
{
    readonly TimeProvider time=clock??TimeProvider.System;
    ConsoleKeyboardPreview? preview;
    long? released,edited;
    char? feedback;
    internal ConsoleKeyboardOverlayView? View=>preview!=null && (preview.Active || released.HasValue && time.GetElapsedTime(released.Value)<TimeSpan.FromMilliseconds(1200))
        ?new(preview,edited.HasValue && time.GetElapsedTime(edited.Value)<TimeSpan.FromMilliseconds(500)?feedback:null):null;
    internal void Clear(){preview=null;released=edited=null;feedback=null;}
    internal void Update(ConsoleKeyboardPreview? value)
    {
        if(value==null){Clear();return;}
        if(value.Active){preview=value;released=edited=null;feedback=null;}
        else
        {
            // Retain the selected wheels between quick gestures, while making
            // it explicit that releasing again cannot type another character.
            preview=preview?.Set==value.Set?preview with{Active=false,Character=null}:value;
            released=time.GetTimestamp();
        }
    }
    internal void Edited(char character)
    {feedback=character;edited=released=time.GetTimestamp();}

    internal static string Draw(string frame,ConsoleKeyboardOverlayView view,string text,bool secret,int columns,int rows)
    {
        columns=Math.Clamp(columns,40,240);rows=Math.Clamp(rows,12,120);
        var marginX=Math.Max(3,(int)Math.Ceiling(columns*.05));var marginY=Math.Max(1,(int)Math.Ceiling(rows*.05));
        var width=Math.Min(94,columns-2*marginX);var height=Math.Min(21,rows-2*marginY);
        var full=width>=68 && height>=21;
        if(!full)height=Math.Min(height,14);
        var canvas=new Canvas(width,height);
        canvas.Border();
        var preview=view.Preview;
        // A retained highlight would reveal the last password character even
        // with a masked Typed label. Clear both selections after secret edits.
        if(secret && !preview.Active)preview=preview with{Left=null,Right=null,Character=null,LeftX=0,LeftY=0,RightX=0,RightY=0};
        var alphabet=ConsoleStickKeyboard.Alphabets[preview.Set];
        var slices=(int)Math.Ceiling(Math.Sqrt(alphabet.Length));
        string Group(int index)=>index*slices<alphabet.Length?alphabet.Substring(index*slices,Math.Min(slices,alphabet.Length-index*slices)).Replace(' ','␣'):"—";
        string Letter(int index)=>preview.Left.HasValue && preview.Left.Value*slices+index<alphabet.Length
            ?Label(alphabet[preview.Left.Value*slices+index]):"—";
        var candidate=preview.Active && preview.Character.HasValue?Label(preview.Character.Value):"—";
        var message=view.Feedback is '\b' or '\x7f'?"Deleted":view.Feedback.HasValue?"Typed: "+(secret?"*":Label(view.Feedback.Value)):"Preview: "+candidate;
        canvas.Center(1,message,Style.Preview);
        // Keep the insertion end visible, without ever including entered secret
        // characters in a terminal frame or a cached overlay view.
        var field="Text: "+text;
        if(field.Length>width-4)field="Text: …"+text[^Math.Min(text.Length,width-11)..];
        canvas.Put(2,2,field,Style.Normal);
        if(full)
        {
            canvas.Center(3,string.Join("   ",ConsoleStickKeyboard.Names.Select((name,i)=>i==preview.Set?"["+name+"]":name)),Style.Muted);
            var leftX=width/4-1;var rightX=width-leftX-1;var centerX=width/2;
            canvas.CenterAt(leftX,5,"LEFT · group",Style.Normal);canvas.CenterAt(rightX,5,"RIGHT · letter",Style.Normal);
            Wheel(canvas,leftX,11,Group,preview.Left,preview.LeftX,preview.LeftY,slices);
            Wheel(canvas,rightX,11,Letter,preview.Right,preview.RightX,preview.RightY,slices);
            canvas.CenterAt(centerX,7,preview.Active?"RELEASE":"HOLD LT/RT",Style.Muted);
            var glyph=view.Feedback is '\b' or '\x7f'?null:view.Feedback.HasValue?(secret?'*':view.Feedback.Value):preview.Character;
            if(glyph.HasValue && Glyph(glyph.Value) is { } shape)
                for(var row=0;row<shape.Length;row++)canvas.CenterAt(centerX,9+row,shape[row].Replace('#','█'),Style.Preview);
            else canvas.CenterAt(centerX,11,glyph.HasValue?Label(glyph.Value):"—",Style.Preview);
            canvas.CenterAt(centerX,15,preview.Active && preview.Character.HasValue?"to type":"no typing",Style.Muted);
            canvas.Center(height-4,preview.Active?"Center either stick / B: cancel":"Hold LT/RT to choose the next character",Style.Normal);
            canvas.Center(height-3,"LB/RB: set   X: delete   Y: space   B: cancel   A: done",Style.Muted);
            canvas.Center(height-2,"● stick   × center/cancel   [choice] selected   ␣ space",Style.Muted);
        }
        else
        {
            canvas.Center(3,ConsoleStickKeyboard.Names[preview.Set]+" · "+slices+" slices",Style.Muted);
            if(height>=14)
            {
                // The same clockwise layout fits narrow terminals with smaller
                // wheels. Short group labels still show every available letter.
                var a=width/4;var b=width*3/4;
                canvas.CenterAt(a,4,"LEFT",Style.Muted);canvas.CenterAt(b,4,"RIGHT",Style.Muted);
                MiniWheel(canvas,a,7,Group,preview.Left,slices);MiniWheel(canvas,b,7,Letter,preview.Right,slices);
            }
            else
            {
                // At 40x12 the safe area cannot fit two wheels. Preserve the
                // candidate, selected group and cancellation before shortcuts.
                canvas.Put(2,4,"L: "+(preview.Left.HasValue?Group(preview.Left.Value):"center / cancel")+"  R: "+(preview.Right.HasValue?Letter(preview.Right.Value):"center"),Style.Normal);
            }
            canvas.Center(height-4,preview.Active?"Release: type · Center/B: cancel":"Hold LT/RT: choose",Style.Normal);
            canvas.Center(height-3,"LB/RB: set · X: del · Y: space",Style.Muted);
            canvas.Center(height-2,"A: done · B: cancel field",Style.Muted);
        }
        var x=(columns-width)/2;var y=(rows-height)/2;
        // Keep each overlay row alongside its background row. The native
        // display client compares chunks beginning at column 1; appending the
        // entire overlay would let a changed background overwrite an unchanged
        // overlay. ANSI dim affects only the backdrop, not the opaque panel.
        frame=frame.Replace("\x1b[0m","\x1b[0;2m").Replace("\x1b[7m","\x1b[2m");
        var starts=Regex.Matches(frame,"\x1b\\[(\\d+);1H");
        var output=new StringBuilder(frame[..starts[0].Index]);
        for(var i=0;i<starts.Count;i++)
        {
            var start=starts[i];var end=i+1<starts.Count?starts[i+1].Index:frame.Length;
            output.Append(start.Value).Append("\x1b[0;2m").Append(frame.AsSpan(start.Index+start.Length,end-start.Index-start.Length));
            var row=int.Parse(start.Groups[1].Value)-1;
            if(row>=y && row<y+height)output.Append(canvas.RenderRow(x,row,row-y));
        }
        return output.ToString();
    }
    static string Label(char c)=>c==' '?"SPACE":c.ToString();
    static void MiniWheel(Canvas canvas,int x,int y,Func<int,string> label,int? selected,int slices)
    {
        for(var i=0;i<slices;i++)
        {
            var angle=i*2*Math.PI/slices;
            var dx=(int)Math.Round(6*Math.Sin(angle));var dy=(int)Math.Round(-2*Math.Cos(angle));
            canvas.CenterAt(x+dx,y+dy,selected==i?"["+label(i)+"]":label(i),selected==i?Style.Selected:Style.Normal);
        }
        canvas.CenterAt(x,y,"×",Style.Muted);
    }
    static void Wheel(Canvas canvas,int cx,int cy,Func<int,string> label,int? selected,double stickX,double stickY,int slices)
    {
        const int rx=14,ry=5;
        for(var y=-ry;y<=ry;y++)for(var x=-rx;x<=rx;x++)
        {
            var radius=Math.Sqrt(x*x/(double)(rx*rx)+y*y/(double)(ry*ry));
            if(radius>1.05 || radius<.28)continue;
            var angle=(Math.Atan2(x/(double)rx,-y/(double)ry)+2*Math.PI)%(2*Math.PI);
            var sector=(int)Math.Floor(angle*slices/(2*Math.PI)+.5)%slices;
            var boundary=Math.Abs((angle*slices/(2*Math.PI)+.5)%1);
            var edge=radius>.9;var spoke=boundary<.055 || boundary>.945;
            var stroke=y==0?"─":x*y<0?"╱":"╲";
            canvas.Put(cx+x,cy+y,edge?"·":spoke?stroke:" ",selected==sector?Style.Wedge:Style.Muted);
        }
        for(var i=0;i<slices;i++)
        {
            var angle=i*2*Math.PI/slices;
            var x=cx+(int)Math.Round(10*Math.Sin(angle));var y=cy+(int)Math.Round(-4*Math.Cos(angle));
            canvas.CenterAt(x,y,selected==i?"["+label(i)+"]":label(i),selected==i?Style.Selected:Style.Normal);
        }
        canvas.CenterAt(cx,cy,"×",Style.Muted);
        // Inner dots use independent coordinates; slice selection retains its
        // hysteresis while the dot makes small thumb movements visible.
        canvas.Put(cx+(int)Math.Round(stickX*6),cy+(int)Math.Round(stickY*2),"●",Style.Preview);
    }
    static string[]? Glyph(char c)
    {
        var index="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".IndexOf(char.ToUpperInvariant(c));
        if(index<0)return null;
        return Fonts[index].Split('/');
    }
    static readonly string[] Fonts=[
        " # /# #/###/# #/# #","## /# #/## /# #/## "," ##/#  /#  /#  / ##","## /# #/# #/# #/## ",
        "###/#  /## /#  /###","###/#  /## /#  /#  "," ##/#  /# #/# #/ ##","# #/# #/###/# #/# #",
        "###/ # / # / # /###","  #/  #/  #/# #/ # ","# #/# #/## /# #/# #","#  /#  /#  /#  /###",
        "# #/###/###/# #/# #","# #/###/###/###/# #"," # /# #/# #/# #/ # ","## /# #/## /#  /#  ",
        " # /# #/# #/ ##/  #","## /# #/## /# #/# #"," ##/#  / # /  #/## ","###/ # / # / # / # ",
        "# #/# #/# #/# #/###","# #/# #/# #/# #/ # ","# #/# #/###/###/# #","# #/# #/ # /# #/# #",
        "# #/# #/ # / # / # ","###/  #/ # /#  /###","###/# #/# #/# #/###"," # /## / # / # /###",
        "## /  #/ # /#  /###","## /  #/ # /  #/## ","# #/# #/###/  #/  #","###/#  /## /  #/## ",
        " ##/#  /###/# #/###","###/  #/ # / # / # ","###/# #/###/# #/###","###/# #/###/  #/## "];
    enum Style{Normal,Muted,Selected,Wedge,Preview}
    sealed class Canvas(int width,int height)
    {
        readonly char[,] chars=new char[height,width];readonly Style[,] styles=new Style[height,width];
        internal void Put(int x,int y,string value,Style style)
        {
            if(y<1 || y>=height-1)return;
            for(var i=0;i<value.Length;i++)if(x+i>0 && x+i<width-1){chars[y,x+i]=value[i];styles[y,x+i]=style;}
        }
        internal void Center(int y,string value,Style style)=>CenterAt(width/2,y,value,style);
        internal void CenterAt(int x,int y,string value,Style style)=>Put(x-value.Length/2,y,value,style);
        internal void Border()
        {
            for(var x=1;x<width-1;x++){chars[0,x]='─';chars[height-1,x]='─';}
            for(var y=1;y<height-1;y++){chars[y,0]='│';chars[y,width-1]='│';}
            chars[0,0]='╭';chars[0,width-1]='╮';chars[height-1,0]='╰';chars[height-1,width-1]='╯';
        }
        internal string RenderRow(int x,int y,int row)
        {
            var output=new StringBuilder($"\x1b[{y+1};{x+1}H");Style? last=null;
            for(var col=0;col<width;col++)
            {
                var style=styles[row,col];
                if(last!=style)
                {
                    output.Append(style switch{Style.Muted=>"\x1b[0;90;40m",Style.Selected=>"\x1b[0;1;30;46m",Style.Wedge=>"\x1b[0;36;44m",Style.Preview=>"\x1b[0;1;96;40m",_=>"\x1b[0;37;40m"});last=style;
                }
                output.Append(chars[row,col]=='\0'?' ':chars[row,col]);
            }
            return output.Append("\x1b[0m").ToString();
        }
    }
}
