#!/usr/bin/python3
"""Compatibility launcher for older Xur bundles; implementation is in xurutil."""
import os,pathlib,sys
native=pathlib.Path(__file__).resolve().with_name('xurutil')
os.execv(str(native),[str(native),'host','migrate',*sys.argv[1:]])
