<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
    <DefaultItemExcludes>$(DefaultItemExcludes);.build/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
